### ISSUE TITLE
Use typecode throughout chapter 4

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#106]
In chapter 4 it is repeatedly noted that the first symbol after $a, $p, $e, or $f is a constant. However that constant has a special role. I suggest changing that to typecode everywhere, and defining typecode as a constant.

@nmegill - seem okay?

**Comment by nmegill** [comment]
OK.

**Comment by david-a-wheeler** [comment]
This is done in #109. All done, closing issue.
