### ISSUE TITLE
Typos/suggestion for example for Weak Deduction Theorem

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#116]
It's already a big improvement that the proof of renegcl is shown as example in Version of 2019-03-07!
However, there are two typos:
- page 95: Step 2: 1re  -> eleq1d
- page 96: "That in, turn, turn converts ..." -> "That in turn converts..."

Instead of the fuzzy descriptions of steps 1-4 ("somewhat strange-looking", technical stuff") they should be described in principle. Here a suggestion for a replacement of the two first paragraphs on page 96, "The somewhat strange-looking steps in renegcl ... in renegcl step 6." (I used the metamath notation for the LaTex formulas):

> Let's briefly look at how renegcl uses the Weak Deduction Theorem (dedth) to do its job, in case you want to do something similar or want understand it more deeply. 
> Starting at the end of the proof of renegcl, the main step dedth is performed, requiring on the one hand the (substituted) deduction renegcli in step 5, which proves that ` A e. RR => |- -u A e. RR `. To fulfill the hypothesis of this version of renegcli (step 4), it is reduced to the already proven theorem ` 1 e. RR ` in step 3.
> On the other hand, the equivalence of the conclusion of renegcl ( ` -u A e. RR ` ) and the substituted conclusion of renegcli must be proven, which is done in steps 2 and 1.

**Comment by avekens** [comment]
Additonal Typo on page 100: "... to reuse already-proven proven assertions..."?

**Comment by david-a-wheeler** [comment]
Going backwards in the description makes sense, but I think if you're going to go that way, you need to emphasize step 2 (because that's what forces the substitutions).  I'll try to rewrite it, inspired by this, and see what you think...!

**Comment by david-a-wheeler** [comment]
I took what you proposed and added what I hope are improvements.  See: #119

Does that do the job?

**Comment by avekens** [comment]
yes, that looks good. However, I want to wait for the PDF to give my final OK.

**Comment by david-a-wheeler** [comment]
Very good.

I'm closing this issue.  If you see more problems, please open a new issue.  That way we'll know that there is "something left to do".
