### ISSUE TITLE
Example for Natural deduction

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#117]
Although I think it is a very good idea to give an example here, I must confess that I do not understand the example given on pages 98-100 (without having/getting additional backgrund information). I think the example is theorem ex-natded5.5 of set.mm (maybe this should be mentioned?). What is the goal of this example? I think the goal is to prove ` ph ->-. ps ` if ` ph -> ( ps -> ch ) ` and ` ph -> -. ch ` , which is the "deduction form" of theorem  ~ mto, saying  `-. ps ` if ` ps -> ch ` and ` -. ch ` . Maybe this should be mentioned at the beginning of the example, maybe in the following way (instead of "An example may make this clearer. The following table shows a simple...")

> An example may make this clearer. In the following, a proof of the "rule of modus tollens" in deduction form is shown. Usually, this "rule of modus tollens" is stated as `-. ps ` if ` ps -> ch ` and ` -. ch ` (see also theorem mto in set.mm). In deduction form, the corresponding theorem would read as  ` ph ->-. ps ` if ` ph -> ( ps -> ch ) ` and ` ph -> -. ch `. The following table shows a simple...

Additionally, it would be helpful to provide the proof of ~ mto to show the differences between theorems in deduction form and in inference form.

**Comment by david-a-wheeler** [comment]
Fair enough, I'll add lots more context.  I don't think adding mto here would help, since that isn't in natural deduction form.

**Comment by david-a-wheeler** [comment]
I've done so in #120 - I think this resolves the issue.

**Comment by avekens** [comment]
At least a big step in the right direction. Again, I want to wait for the PDF to give my final OK.

**Comment by david-a-wheeler** [comment]
The change in #120 has been merged.  You can see exactly what was changed here:

https://github.com/metamath/metamath-book/pull/120/files

I'm closing this issue.  If you think more needs to be done, please just open a new issue and explain what else is needed.  It's easier to track things with separate issues.  Otherwise it'll be easy for something to get lost and I don't want that to happen.
