### ISSUE TITLE
EBNF typo

### ISSUE THREAD

**Issue by benjub** [metamath/metamath-book#118]
On p.206, I would replace

variable variable variable* --> variable variable+

and consequently, on the line above,

"variable*" is empty for them --> "variable+" is a single variable for them

**Comment by david-a-wheeler** [comment]
They are equivalent technically, but I intentionally did it this way. The two variable case is in some ways more fundamental, so I wanted to make it very clear and distinct.

**Comment by benjub** [comment]
As you prefer.  But isn't that an argument for never using v+ as a shortcut for v v* ?  Look at the statement just above:

/* Variable symbols declaration. */
variable-stmt ::= ’$v’ variable+ ’$.’

You could similarly write "Simple variable statements only have one variable, i.e., "variable*" is empty for them.

Anyway, that's a nitpick. You be the judge.

**Comment by david-a-wheeler** [comment]
Normally I *would* write variable+, and I do so elsewhere.  But in most cases it doesn't matter if there are 2 vs. 3 or more.  In this particular situation there *is* something special about having exactly 2, so I wanted the EBNF to hint at that.  Implementations are likely to need a branch condition that handles "exactly 2 variables" differently from "more than 2 variables", and if the EBNF is written this way, implementations can more closely match the definition here without issue.

It's not wrong either way - it's style choice - and I hope I've justified the choice :-).  So I'm closing this one.

**Comment by david-a-wheeler** [comment]
You could certainly say the same with the 1-variable case.  But a distinction between 1 vs. more-than-1 is unremarkable; that happens in many situations.  2 vs.  more-than-2 is a less common distinction, so I thought it'd be best to emphasize it by using the notation in a different way.
