### ISSUE TITLE
write source ... /split

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#121]
In section 5.3.2, it is (still) mentioned that
"Note: The present version of Metamath will not split the database into its constituent source files included with $[ and $] keywords. A future version is planned to properly separate all constituent files."

This future version is already available! So we should describe the new option /split here (or at least mention it). 
Additionally, the options must be updated anyway. Calling help write source in metamath.exe I get:

Syntax:  WRITE SOURCE <filename> [/ FORMAT] [/ REWRAP] [/ SPLIT]
           [/ KEEP_INCLUDES] [/ NO_VERSIONING]

This command will write the contents of a Metamath source (previously
read with READ) into a file
(or multiple files if / SPLIT is specified).

Optional qualifiers:
    / FORMAT - Reformats statements and comments according to the
        convention used in the set.mm database.  Proofs are not
        reformatted; use SAVE PROOF * / COMPRESSED to do that.
        Incidentally, SAVE PROOF honors the SET WIDTH parameter
        currently in effect.
    / REWRAP - Same as / FORMAT but more aggressive.  It unwraps the
        lines in the comment before each $a and $p statement, then it
        rewraps the line.  You should compare the output to the original
        to make sure that the desired effect results; if not, go back to
        the original source.  The wrapped line length honors the
        SET WIDTH parameter currently in effect.  Note:  Text
        enclosed in <HTML>...</HTML> tags is not modified by the
        / REWRAP qualifier.
    / SPLIT - Files included in the source with $[ <inclfile> $] will be
        written out separately instead of included in a single output
        file.  The name of each separately written included file will be
        <inclfile> argument of its inclusion command.
    / KEEP_INCLUDES - If a source file has includes but is written as a
        single file by omitting / SPLIT, by default the included files will
        be deleted (actually just renamed with a ~1 suffix unless
        / NO_VERSIONING is specified) to prevent the possibly confusing
        source duplication in both the output file and the included file.
        The / KEEP_INCLUDES qualifier will prevent this deletion.
    / NO_VERSIONING - Backup files suffixed with ~1 are not created.

The option /clean seems to not exist anymore, but there are additional new options (besides /split). Therefore I suggest tu update section 5.3.2 accordingly.

**Comment by david-a-wheeler** [comment]
Agreed.

**Comment by david-a-wheeler** [comment]
@avekens - #124 should resolve this.  Thanks for reporting it!
