### ISSUE TITLE
Update section 4.4.2 Comment Markup Notation for HTML

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#126]
- the version number of the Metamath program should be removed
- the list of markup-features should be updated according to the current output for help language in metamath.exe. The following items are missing:
         < HTML >...< /HTML >" - do not convert "<" and ">" enclosed
             in these tags.  All other markup processing is normal.
             (These tags may be replaced by a space in the HTML
             output, so don't use them in the middle of a word.)
         (Contributed by < author >, < date >.)
         (Revised by < author >, < date >.)
         (Proof shortened by < author >, < date >.)
             The above dates are checked by VERIFY MARKUP.
         (New usage is discouraged.)
         (Proof modification is discouraged.)
             See HELP SHOW DISCOURAGED and HELP SET DISCOURAGEMENT.
       Note:  Comments may not be nested.

- by the way: VERIFY MARKUP,  SHOW DISCOURAGED and SET DISCOURAGEMENT are also not mentioned/explained yet!

**Comment by david-a-wheeler** [comment]
> VERIFY MARKUP, SHOW DISCOURAGED and SET DISCOURAGEMENT are also not mentioned/explained yet!

I have no *objections* to adding that, but I don't think the book needs to list *everything* the Metamath program can do.  They can always run "help ..." to see that information.  In set.mm, it will be run automatically.

I've already done a number of related things, so I propose that we close this issue.

**Comment by avekens** [comment]
I had a look at the changes, they are fine! Therefore, I close this issue.
