### ISSUE TITLE
Examples for "forms" of theorems

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#132]
Hi David, with the 2019-04-07 version we are very close to a "fixed version" - thanks a lot for your magnificient work so far. Especially the list of "forms" at the beginning of section 3.9.3 is very useful. As I always like to have examples, showing the decribed general principles more vividly, I would propose to add some examples here, too.

I would suggest the following (which can be understood easily without additional explanations):
closed form:
    unss $p |- ( ( A C_ C /\ B C_ C ) <-> ( A u. B ) C_ C ) $=
deduction form:
    unssd.1 $e |- ( ph -> A C_ C ) $.
    unssd.2 $e |- ( ph -> B C_ C ) $.
    unssd $p |- ( ph -> ( A u. B ) C_ C ) $=
inference form:
    unssi.1 $e |- A C_ C $.
    unssi.2 $e |- B C_ C $.
    unssi $p |- ( A u. B ) C_ C $=

Regards,
Alexander

**Comment by david-a-wheeler** [comment]
I have a pull request that does it.  I decided to use the & ... => notation; we don't really need to know the names of the individual hypotheses for the purpose of this example.
