### ISSUE TITLE
New Version finalized?

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#136]
Is the revision of the Metamath book finalized now? Any open issues/todos?

One (final, if nothing else will change) remark: Please add my middle initial to my name on page 30: Alexander W. van der Vekens . Usually I do not use it (and nobody else has to), but in an official publication like a book I would like to see it. After this, the book looks fine for me.

I am eagerly awaiting the final version, so that I can get a printout/bound book of it.

**Comment by david-a-wheeler** [comment]
This will be fixed if #137 is accepted.  After that I think we should "ship it" - but Norm has the final say.

**Comment by david-a-wheeler** [comment]
Fixed!  We have a few last-minute errata reports & then we hope to print a paper book.
