### ISSUE TITLE
Typos found by Benoît Jubin in chapters 2-3

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#142]
Benoît Jubin found typos in chapters 2-3.
He found them a while back, so some may have been resolved.
My understanding is that he will modify the TeX soon, but I don't want these lost.

~~~~
48, 8: Let us let --> Let
50, 1: don't what know --> don't know what
73: that is there --> that is, there
73: for proving any expression --> for converting any expression
73, -3: "(We do not define \bottom in set.mm.)" --> "(It is actually df-fal
in set.mm.)"
74: to help you to become --> to help you become [although both are
correct, I think]
76, 12: I would write: interpreted as \neg(\varphi(x|y)) or
(\neg\varphi)(x|y) [Note that the Metamath convention is the convention
used by Bourbaki: they use "(x|y)ph" and write that it should be read "x
replaces y in ph".]
79: df-v and df-nul: in pretty-print, slanted V --> \mathrm{V}, and
verbatim: V --> _V [maybe other occurrences in the pdf e.g. df-rel,
df-res, (86, 9), isset, canth.1, inex1.1, inex, 0ex, prex, onprc, omex,
(87, 4), (87, 6), (91, -5)]
79: df-pw: P~ --> ~P [twice]
81, 4: is not ambiguous --> creates no ambiguity
81, 9: Note that x, y, and z must be distinct but... --> Note that z must
be distinct from x and y and must not occur in \varphi (but x and y may be
identical and may appear in \varphi) [it is strange that this
consideration appears only here, and not for the other definitions or
axioms, but for now maybe it's enough]
81: df-eprel: slanted E --> \mathrm{E}
82, 2: Define class --> Define the class
82: Define the cross product --> Define the cross product (or Cartesian
product) ["Cartesian product", or "direct product", are way more common
the "cross product"]
82: df-rn has changed (it is now defined as the domain of the converse)
83: df-rel should go right after df-xp, and before df-dm
83: co-domain --> codomain
88, -9: tfr1 states --> Theorem tfr1 states [avoid beginning a sentence
with a symbol; same with tfr2, tfr3]).
89: at ordered pair --> at the ordered pair
89, -6 and -8: by statement --> either "by the statement" or "by
Statement" [capitalized]
90, Item 15: a negative --> a real negative
90, Item 16: a reciprocal --> a real inverse
102: contain a string --> contains the string
105: update outputs of MM> show statement prth/full and MM> show proof
prth/essential/lemmon/renumber (and probably others)
107: if we want --> if we wanted
107: There may be a sense... --> Provided that the proof is in some sense
``optimal'', there may be a sense...
107: as redundant : why "redundant" ? (on the other hand, in the following
line, "intrisic interest by itself" : "intrinsic" is redundant with "by
itself")
108: Is this subsection (3.10.1) up to date ?
~~~~

**Comment by benjub** [comment]
Thanks @david-a-wheeler . In the previous list of errata and this one, the references (page x, line y) correspond to the pdf with date 2019-05-20.

Here are typos for the TOC, Preface, and Chapter 1.

TOC: capitalization of some section titles missing: 1.3.5, 1.3.6, 3.2.4, 3.3.2, 3.9.3
TOC: 3.3.2, 3.3.3: hyphen should be a dash, either spaced en dash ~--~ or non-spaced em dash ---
xv, mid-page: “relative” to the universe U (κ)” --> “relative to the universe U(κ)”
xvi, mid-page: 1-8 --> 1--8
xvi, -7: appendix --> Appendix
8, 12: no where --> nowhere
9, footnote: a collection --> the collection
12: *** --> remove ? (it's apparently the only place in the book this symbol appears)
15: Gödel's incompleteness theorem --> The mere statement of Gödel's incompleteness theorem (to avoid possible ambiguity)
26, -6: primary --> primarily
29, 6: on-going --> ongoing
31: documentor --> documenter
35: in the combination --> the combination
35: to reassembled --> to be reassembled

**Comment by david-a-wheeler** [comment]
Ok. I would like to get this done over this (long) weekend. If you can keep posting comments like this, I will work to fix the corresponding TeX as pull requests for Norm to approve.

I'd prefer that you create new pull requests for each new batch of fixes. Doing that will make it easier to track. I want to make sure that I don't skip any batch.

**Comment by david-a-wheeler** [comment]
>> Russell's paradox assumes that there exists a set $S$ that is a collection of all sets that don't contain themselves.

> 9, footnote: a collection --> the collection

I think "a" is fine in this context.

**Comment by david-a-wheeler** [comment]
I've posted a pull request to address the TOC+chapter 1 issues: https://github.com/metamath/metamath-book/issues/142

I intend to do the chapters 2-3 later (unless Benoît Jubin soon makes a pull request himself).

**Comment by benjub** [comment]
Here are additional typos/suggestions for Chapter 3 (references to metamath.pdf dated 2019-05-24).
I skimmed very fast over the new material in the book, so I have probably missed some typos.

86, 9: use \mathrm{V} (and many times on p.87, e.g. statement of isset, inex)
86, -8: In Principia Mathematica: add comma (?)
86, -5: At the time of this writing --> As of... and add comma (?)
91, 9: In set.mm: add comma (?)
91, -9: weakened them (by ...) --> weaken them (by proving the stronger version from the weaker one (together with some more basic axioms))
91, -5: axiom $\C \in V$: use \mathrm{V}, but more importantly: remove this bullet point? (it is not properly speaking a complex number axiom, and accordingly, its proof uses axioms of set theory)
91: bullet list: indicate the metamath labels of the theorems showing said redundancy? add the turnstile (as is done for the other statements)?
92: indent more the column "Expression"? There are extra spaces after some opening parentheses, before some closing parentheses, and before some commas; the hyphen and the "if" are sometimes separated by a comma, sometimes not
93: In the html display: add comma (?)
95, 1: proof of the deduction --> the proof of the deduction theorem/form (?) (not clear); driven --> find a more explicit verb?
95, 2: againstarting, axiomsin : spaces missing
95, mid-page (formula): "if " is wrongly in italics
96,10: By itself --> add comma (?)
96: called\`\`deduction: space missing
96: Today: add comma (Actually, "Today there is a preference" sounds very general... "We now prefer to write" ?)
96: remove "something called"
96: Applying this approach is called “deduction style.” --> We call this approach ``deduction style.''
98: very limited set of --> a very limited set of
98: Jakowski --> Ja\'{s}kowski (several times)
98: As reconstructions: add comma (?)
98: Indrzejczak: add space after it
98: Usually it requires --> Usually, it requires (?)
98: etc. : add comma before (?)
100: In Metamath: add comma (?)
101: Mario’s --> Carneiro's
104: theorem id1 --> Theorem id1 (also p.104: statement id1 --> Statement id1, and possibly other instances where a theorem/statement/axiom is referred by its name).
108: Title of the subsection: add "the" before "compact" ?
108: is this subsection up to date?
108, -1: reference to Chapter 2 seems wrong, or at best no precise enough

**Comment by david-a-wheeler** [comment]
@benjub - thanks so much for the typo reports!!  I'll fix them.  From now on, can you please create new issues for each new set of issues?  Otherwise it will be easy for me to accidentally miss a set of changes, and I want to make sure I get them all.

**Comment by david-a-wheeler** [comment]
I did the "TOC+chapter 1" batch. To be done is the "ch 2-3" batch and the "ch3" batches listed here.

**Comment by david-a-wheeler** [comment]
> (page) 79: df-v and df-nul: in pretty-print, slanted V --> \mathrm{V}, and verbatim: V --> _V [maybe other occurrences in the pdf e.g. df-rel, df-res, (86, 9), isset, canth.1, inex1.1, inex, 0ex, prex, onprc, omex, (87, 4), (87, 6), (91, -5)]

These go all over the document, so I will fix these concerns on a new branch called benoit-v .

It's true that `\m{V}` is not correct, but I'm trying to make sure the sequence is the same as generated by the tool.  That isn't `\mathrm{V}`, it's `\m{{\rm V}}` .  You can confirm this by running:

~~~~sh
metamath 'read set.mm' 'open tex ,1' 'show statement df-v /old_tex' quit
~~~~

You're right the verbatim text is wrong.  I changed `V` to `_V` is the few cases where verbatim occurred, but the verbatim doesn't occur in many places.   For technical reasons in LaTeX this has to be represented as `{\char\`&#96;`\_}V`

We already note in the one section with all the verabatim examples why do we that (it doesn't happen everywhere).  But I'll add after this existing text:

> If you are in doubt, use the \texttt{show statement}\index{\texttt{show statement} command} command  in the Metamath program to see the full statement.

The following text:

> A selection of this notation is summarized in Appendix~\ref{ASCII}.

... and I'll add `_V` to the list of summarized notation in the appendix.

**Comment by david-a-wheeler** [comment]
> 91: bullet list: indicate the metamath labels of the theorems showing said redundancy? add the turnstile (as is done for the other statements)?

I'll add a cross-reference to the labels.  I won't add the turnstyle, and I'll leave the formatting as-is.  The difference in formatting won't cause any trouble in understanding, but it *does* indicate to the reader that there's something different about the list.

**Comment by david-a-wheeler** [comment]
TODO:

> 83: df-rel should go right after df-xp, and before df-dm

**Comment by david-a-wheeler** [comment]
> 90, Item 16: a reciprocal --> a real inverse

I'll change it to "real reciprocal".  The term "inverse" is absurdly overloaded, while reciprocal is more specific. But you're right that the expression requires a real, so let's note that.

**Comment by david-a-wheeler** [comment]
TODO:

> 105: update outputs of MM> show statement prth/full and MM> show proof
prth/essential/lemmon/renumber (and probably others)

**Comment by david-a-wheeler** [comment]
> 86, -8: In Principia Mathematica: add comma (?)

I think it's fine without the comma.  You wouldn't normally pause there in speech..

**Comment by david-a-wheeler** [comment]
> 92: indent more the column "Expression"? There are extra spaces after some opening parentheses, before some closing parentheses, and before some commas; the hyphen and the "if" are sometimes separated by a comma, sometimes not

I don't know what you mean here. My page 92 is the 2+2=4 proof, which doesn't have this.  I guess you mean the 3.9.2 Weak Deduction Theorem proof, but I don't see a comma separating hyphens and ifs.  The spacing is too hard to control to be worth worrying about.

**Comment by david-a-wheeler** [comment]
> 93: In the html display: add comma (?)

I don't think that's necessary.

**Comment by david-a-wheeler** [comment]
> 95, 2: againstarting, axiomsin : spaces missing

That's an em dash, you don't put spaces around em dashes.  There might have been a generator problem, the original code used UTF-8, I've changed it to the standard TeX expression for em dashes.

**Comment by david-a-wheeler** [comment]
> 96,10: By itself --> add comma (?)

I don't think that's necessary.

**Comment by david-a-wheeler** [comment]
>104: theorem id1 --> Theorem id1 (also p.104: statement id1 --> Statement id1, and possibly other instances where a theorem/statement/axiom is referred by its name).

I don't agree.  The words "statement" and "theorem" are usually not part of the name, and thus shouldn't be capitalized. (There are exceptions such as the Deduction Theorem, but they are exceptions.) The name itself (such as "id1"), could in theory be capitalized, but it's a lowercase name in a case-sensitive system, so the name should not be capitalized either.

**Comment by david-a-wheeler** [comment]
TODO:

> 108: is this subsection up to date?

It's going to take me some effort to cross-check that.

**Comment by david-a-wheeler** [comment]
I believe I've done everything in this issue except the TODOs, which, well, are still to be done.  I plan to go back to them after taking a crack at the other issues.

**Comment by david-a-wheeler** [comment]
TODOs still to do:

> 86, -5: At the time of this writing --> As of... and add comma (?)

I think so, but I wrote a script to do the counting (for the direct not recursive case) and am analyzing the current version of set.mm.  Once I get the answers I can stick that in a footnote.  If it's not the top, I can re-run to see the direct + indirect case.

> 105: update outputs of MM> show statement prth/full and MM> show proof
prth/essential/lemmon/renumber (and probably others)
> 108: Is this subsection (3.10.1) up to date ?
> 108: is this subsection up to date?

**Comment by david-a-wheeler** [comment]
(Whew! I tried to get through all the comments today.  I didn't succeed, but I did get a vast majority of them done.  I'm going to try to do the rest as quickly as I reasonably can.)

**Comment by david-a-wheeler** [comment]
I believe everything is done, so I'm closing this issue.
