### ISSUE TITLE
Typo: stronger --> weaker

### ISSUE THREAD

**Issue by benjub** [metamath/metamath-book#145]
I have other minor typos I'll try to report ASAP, but I think this one could lead to misunderstandings, so I report it here without delay (I have not yet cloned metamath-book on git, so I cannot yet do PRs).
On page 195, it is written "metalogical independence is a stronger requirement than independence".
Obviously, "stronger" should be "weaker".

**Comment by david-a-wheeler** [comment]
Thanks!  If you just please post typos as issues, I can turn them into Tex.  I'm trying to get everything done this weekend. No need to clone.

**Comment by david-a-wheeler** [comment]
@nmegill - comments?

**Comment by nmegill** [comment]
@benjub maybe you are right but I'm a little confused.  An axiom can be metalogically independent without being logically independent e.g. ax-12.  What is your reasoning for calling this weaker instead of stronger, or are the two independence types even comparable in a weaker/stronger sense?

**Comment by benjub** [comment]
@nmegill You made me re-read what I wrote!  But I stand by it. We have two relations among sets of schemes: the traditional one, at the object level, let's call it entailment, and the one you defined, let's call it meta-entailment. As you noted, meta-entailment implies entailment (i.e. if one can prove a scheme from some set of schemes, at the meta-level, then at the object level, one can prove all instances of that scheme from all instances of this set of schemes). Therefore, metacompleteness of a set of schemes is a stronger property than completeness, and meta-independence is a weaker property than independence. Your example of ax-12 shows that meta-independence is actually strictly weaker than independence: ax-12 is meta-independent (as proved my Monk) but not independent. (Simple analogue: being a rectangle is a strictly weaker requirement than being a square.)
What is certainly true, on a subjective level, is that the relation of meta-entailment is harder to grasp, and as a consequence, typical proofs of metacompleteness and of meta-independence will be "harder" to find.

**Comment by nmegill** [comment]
@david-a-wheeler I'll accept @benjub's explanation.  So we should change it to "weaker".
