### ISSUE TITLE
Typos for Chapter 4

### ISSUE THREAD

**Issue by benjub** [metamath/metamath-book#148]
Here are some typos for Chapter 4. The (page, line) references are made to metamath.pdf dated 2019-05-24.
Thanks @david-a-wheeler ; take them with a grain of salt, maybe some suggestions are not so good after all...

Suggestion: Add a note somewhere in the book for non-native English speakers, reading something like:
A note on the English language for non-native speakers: the operation of "substituting y for x" in "x = 2" yields "y = 2". This is equivalently termed "substituting x with y" or "replacing x with y" or "replacing x by y".
[I might have gotten this wrong... which shows that such a remark could be useful. Also, you will certainly find a better wording than me.]

109: bound-variable clashes --> disjoint variable clashes (?)
110: the 94 printable ASCII characters --> the 94 printable ASCII characters other than the space
110: the 93 printable standard ASCII characters other than $ --> the 93 printable ASCII characters other than the space and $
110: white space characters --> whitespace characters (might need to allow hyphenation)
111,2: $( begins --> The auxiliary keyword token $( begins [in order to avoid beginning a sentence with a symbol]
111,3: the 94 printable characters and white space --> the 95 printable characters (including space)
111: As is any reference to the top-level file. --> As is any reference to the top-level file (to avoid loops).
111,-11: ${ begins --> The keyword token ${ begins [to avoid beginning a sentence with a symbol]
111,-4: $. token : the space looks too big (several times; might need a \ in the TeX)
111-112: tiny remark: when in boldface, the symbols $v, $c etc... are not in typewriter font.
112: A $a --> An $a (?)
114: strings of printable characters --> strings of nonspace printable characters (?)
121: when free variables --> when the free variables
122: the worse that will happen --> the worst that could happen (?)
123: "contact me if interested": is it possible to give a pointer to these axioms?
123: a $e --> an $e (?) similarly for "$a" and "$f" ?
127: The third property... The last property: there are only three bullet points, not four, and furthermore none is about $d... not clear.
129: whenever assertion mp --> whenever Assertion mp
129: start and end of a frame --> start and end of an extended frame
130: sequence of frames --> sequence of extended frames
130: I noticed that both "inside" and "inside of" are used in the book. I thought "inside" (without "of", unless "inside" is a noun) was the formal way, but I may be wrong.
133: Suggestion: an assertion label is like an operation --> an assertion label is like an operation (more precisely, an $n$-ary operation when the assertion has $n$ \$e-hypotheses).
133: Suggestion: Example 1,2,2,+,+: it might be clearer to have two different operations, e.g.: the input sequence $2, 1, 2, +, \times$ results in $2, 3, \times$ which results in~6.
134: The proof of statement wnew --> The proof of Statement wnew (capitalization)
135: hypothesis wp --> Hypothesis wp
135: it checks to see that the contents of stack location 1 is the same as the math symbol sequence in the $p statement --> it checks to see that the stack contains exactly one element and that this element is the same as the math symbol sequence in the $p statement
136: /essential : isn't it the default behavior now ? (and above, should have used /all)
137: between any two tokens in a source file --> between any two tokens (or at the beginning or end) in a source file
139: applied from --> applied to
147: self reference --> self-reference
148, 1: upper case letters --> uppercase letters
148: recoverable --> fixable (?)
151, footnote: df-oadd has changed (as a result of the definition df-mpt); df-rfg has been replaced by df-rdg, itself using df-recs

**Comment by david-a-wheeler** [comment]
Excellent! I have set aside this afternoon to turn your comments into changes in the TeX file. I'll post replies in the relevant issue if I disagree with something, so we can discuss it.

**Comment by david-a-wheeler** [comment]
>  Suggestion: Add a note somewhere in the book for non-native English speakers, reading something like: A note on the English language for non-native speakers: the operation of "substituting y for x" in "x = 2" yields "y = 2". This is equivalently termed "substituting x with y" or "replacing x with y" or "replacing x by y". [I might have gotten this wrong... which shows that such a remark could be useful. Also, you will certainly find a better wording than me.]

It doesn't matter if the reader is a native English speaker or not.  Even natives can be confused by the similar terminology.  So I've modified the text explaining df-sb to note the different wordings, and I've added a little "trick" that I find useful in helping to remember the correct order.

**Comment by david-a-wheeler** [comment]
> 110: the 94 printable ASCII characters --> the 94 printable ASCII characters other than the space
> 110: the 93 printable standard ASCII characters other than $ --> the 93 printable ASCII characters other than the space and $

The space character is indeed considered a "printable" character per: 

* https://www.juniper.net/documentation/en_US/idp5.1/topics/reference/general/intrusion-detection-prevention-custom-attack-object-extended-ascii.html
* https://en.wikipedia.org/wiki/ASCII#Printable_characters

I'll try to make that clearer.

**Comment by david-a-wheeler** [comment]
>  111-112: tiny remark: when in boldface, the symbols $v, $c etc... are not in typewriter font.

The default typewriter fonts of LaTeX don't support that.  Discussion here: https://tex.stackexchange.com/questions/215482/how-do-i-get-texttt-with-bold-face-in-latex

It's possible to fix but not clear it's worth it.

**Comment by david-a-wheeler** [comment]
> A $a --> An $a (?)

I'm going to leave this as-is.  The rule is what the "next sound" is.  I pronounce this as "A dollar-A", so "A" is correct.

**Comment by david-a-wheeler** [comment]
> 122: the worse that will happen --> the worst that could happen (?)

Not there any more.

**Comment by david-a-wheeler** [comment]
> 123: "contact me if interested": is it possible to give a pointer to these axioms?

@nmegill - Is there one? Could we make such a page & give it a URL? It could be expanded later.

**Comment by david-a-wheeler** [comment]
> 134: The proof of statement wnew --> The proof of Statement wnew (capitalization)
> 135: hypothesis wp --> Hypothesis wp

I'm not doing that in general.  In English you capitalize a proper name unless there's a compelling reason to do otherwise.  The name isn't "Statement X", it's just X.  In our case the names are defined as being lowercase, and the case matters, so I'm not making them uppercase either.

**Comment by nmegill** [comment]
> > 123: "contact me if interested": is it possible to give a pointer to these axioms?
> 
> @nmegill - Is there one? Could we make such a page & give it a URL? It could be expanded later.

@david-a-wheeler You can take out "contact me if interested" and use the URL:
http://us.metamath.org/mpeuni/mmzfcnd.html

**Comment by david-a-wheeler** [comment]
> 151, footnote: df-oadd has changed (as a result of the definition df-mpt); df-rfg has been replaced by df-rdg, itself using df-recs

I think the footnote about df-oadd needs to move into the body.  The use of seq, etc., is key to how set.mm works, and rec doesn't otherwise appear in the literature.  We also need to make it clear that Metamath *could* do it the traditional way.  This will need to be its own pull request.

**Comment by david-a-wheeler** [comment]
> 151, footnote: df-oadd has changed (as a result of the definition df-mpt); df-rfg has been replaced by df-rdg, itself using df-recs

Resolving this took a lot more time.  I ended up moving text out of the footnote & expanding it.  Hopefully Norm will like the result!

**Comment by david-a-wheeler** [comment]
> @david-a-wheeler You can take out "contact me if interested" and use the URL:
http://us.metamath.org/mpeuni/mmzfcnd.html

Done.

**Comment by david-a-wheeler** [comment]
I think everything in this issue has been turned into a pull request.
