### ISSUE TITLE
Address MMOM redux thread (explain $j material)

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#15]
~~~~
  6/15/15  metamath.tex metamath.exe
    9:10 AM mmgrp email Re: [Metamath] MMOM redux thread (***SEE 6/15/15 EMAIL)
    (BTW, the metamath.pdf is not clear on precisely where white space is allowed
    in the $t syntax.)
~~~~

**Comment by david-a-wheeler** [comment]
See the thread here:
https://groups.google.com/forum/#!searchin/metamath/MMOM%7Csort:date/metamath/QE0lwg9f5Ho/PzPPuO47JXoJ

**Comment by david-a-wheeler** [comment]
Norman Megill said on Fri, May 23, 2014 at 10:05 PM (Re: mmj2 tags in comments):

~~~~
What about this idea:  any comment starting with $j (or maybe $m?) would
be reserved for mmj2 use, analogous to the way that a comment with a $t
is reserved for use by typesetting definitions.  What goes inside the
comment would be whatever syntax you want, although lines should be < 80
chars long.  Ideally it would tolerate variable whitespace and
line wrapping, but that's not absolutely required.
~~~~

**Comment by nmegill** [comment]
My to-do note was intended to address whether $t needs to be surrounded by whitespace (I would recommend yes, for simplicity).  Also, it isn't clear whether anything other than whitespace can go between the start of the comment and the $t (I would recommend no, for simplicity).  In the current metamath.exe, I believe that neither of these cases are currently enforced, but I can add code to 'verify markup' to enforce them.

As for $j, that is an mmj2 thing and isn't checked by 'verify markup'.  I don't know what the legal syntax for this ended up being.  If @digama0 remembers perhaps I can add a check to 'verify markup'.  But we don't necessarily have to mention $j in the book right now.

**Comment by digama0** [comment]
Actually my hope is that $j is accepted as a generic "extension" comment, not specific to mmj2. For verifiers that recognize the construct at all, they can support any subset of existing $j commands, as long as they ignore unknown command names.

**Comment by digama0** [comment]
The actual syntax for $j is intentionally similar to $t. It has the form `command arg arg ... ;` where `arg` can be a quoted string or a keyword. I forget at the moment what the valid keywords are - they could just be any string of alphanumeric characters, and we leave the more specific parsing to the commands themselves. The important part is that if a verifier doesn't recognize a command it can skip it and find the end.

**Comment by david-a-wheeler** [comment]
Oh, I see. In that case, I think the *REAL* issue is to add some discussion about `$j`.

I'll post a PR that tries to do that.

**Comment by david-a-wheeler** [comment]
> (1) My to-do note was intended to address whether $t needs to be surrounded by whitespace (I would recommend yes, for simplicity).

That would require rewriting all the $t statements, and current code already handles it.   Personally I'd leave it be, but it's up to you.

> (2) Also, it isn't clear whether anything other than whitespace can go between the start of the comment and the $t (I would recommend no, for simplicity). In the current metamath.exe, I believe that neither of these cases are currently enforced, but I can add code to 'verify markup' to enforce them.

I like that idea (idea 2), and set.mm already meets that criteria.

Should I try to add at least "only whitespace before `$t` rule (idea 2) to the text?

**Comment by david-a-wheeler** [comment]
We're mixing the discussion about `$t` with `$j`, and that is confusing.  I'll create a new issue for `$t`, and have this continue to discuss `$j`.
