### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by benjub** [metamath/metamath-book#150]
* Maybe, search globally for "present version", "future", "current" to check that things are up-to-date, and write instead things like "up to Version...", "from Version...".

* Maybe, write somewhere: "This version of the Metamath book uses the version ... of the Metamath program." (Though it looks like several output displays should be put up-to-date).

* The exact quotation by Saint-Exupéry (quoted on p. 183) is:

« Il semble que la perfection soit atteinte non quand il n’y a plus rien à ajouter, mais quand il n’y a plus rien à retrancher. »
Antoine de Saint-Exupéry, Terre des hommes, chapitre III: L'avion, 1939.

The book "Terre des hommes" (Men's Land) was translated in English as "Wind, Sand and Stars".
My translation of the quote:
It seems that perfection is reached not when there is no longer anything more to add, but when there is no longer anything more to take away.

**Comment by avekens** [comment]
I have  a similar remark in direction of the first bullet point of Benoit: Chapter 1, Introduction starts with "In the past century". Which century is meant? I think it's the 19th century (starting with Gauss, Bolzano, Cauchy, etc.) , so it must read "In the past two centuries...".

**Comment by david-a-wheeler** [comment]
> Maybe, search globally for "present version", "future", "current" to check that things are up-to-date, and write instead things like "up to Version...", "from Version...".

@nmegill - can you do that & tell me if something has changed?  I don't necessarily know what's changed.

> Maybe, write somewhere: "This version of the Metamath book uses the version ... of the Metamath program." (Though it looks like several output displays should be put up-to-date).

In principle I agree, but that's too much work for not enough benefit.

> The exact quotation by Saint-Exupéry (quoted on p. 183) is: ...

We don't need the exact French here, and the translation is cited.  I think the cited translation is far more popular in English anyway. So I think it's fine as-is.

**Comment by david-a-wheeler** [comment]
> I have a similar remark in direction of the first bullet point of Benoit: Chapter 1, Introduction starts with "In the past century". Which century is meant? I think it's the 19th century (starting with Gauss, Bolzano, Cauchy, etc.) , so it must read "In the past two centuries...".

I think it's better to remove "In the past century" completely.  New phrasing:
~~~~
-In the past century, brilliant mathematicians have discovered almost
+Brilliant mathematicians have discovered almost
 unimaginably profound results that rank among the crowning intellectual
 achievements of mankind.  However, there is a sense in which modern abstract
 mathematics is behind the times, stuck in an era before computers existed.
~~~~

I'll turn that into a separate PR.

**Comment by david-a-wheeler** [comment]
The only thing left in this issue is to hear from Norm about "present version", "future", "current".

**Comment by nmegill** [comment]
> > Maybe, search globally for "present version", "future", "current" to check that things are up-to-date, and write instead things like "up to Version...", "from Version...".
> 
> @nmegill - can you do that & tell me if something has changed? I don't necessarily know what's changed.

There are a number of changes needed.  I will try to update all of these today.

**Comment by nmegill** [comment]
> > > Maybe, search globally for "present version", "future", "current" to check that things are up-to-date, and write instead things like "up to Version...", "from Version...".
> > 
> > 
> > @nmegill - can you do that & tell me if something has changed? I don't necessarily know what's changed.
> 
> There are a number of changes needed. I will try to update all of these today.

These are updated in commit 11dc660.

BTW the book is looking great!   @david-a-wheeler  has done a much better job than I could have handled alone.  David, I think we should have a specific acknowledgment to @benjub - could you do that at some point?  Others have also contributed some corrections, perhaps they should be mentioned (maybe a list)?

**Comment by david-a-wheeler** [comment]
@nmegill - great minds think alike!  I'm working on a "Note Added" right now to credit the hard work of Benoit Jubin (I'm currently looking up how to do his name's circumflex in LaTeX).

**Comment by david-a-wheeler** [comment]
@nmegill - thanks for the compliment!!

The "Notes" add credits to people, so I think that covers it.  We also include them in the index if people want to look up their own name.

I think we're done with this issue, so I'm closing it.  Please re-open if there's something in it that still needs doing.
