### ISSUE TITLE
Does Proof Assistant verify $d now?

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#189]
Under "prove" we have:
> Note:  In the present version of
Metamath\index{Metamath!limitations of version 0.07.30}, the Proof
Assistant does not verify that \texttt{\$d}\index{\texttt{\$d}
statement} restrictions are met as a proof is being built.  After you
have completed a proof, you should type \texttt{save new{\char`\_}proof}
followed by \texttt{verify proof} {\em label} (where {\em label} is the
statement you are proving with the \texttt{prove} command) to verify the
\texttt{\$d} restrictions.

@nmegill - Is this still true? I think it is, but if it's obsolete we should remove it.

**Comment by nmegill** [comment]
Unfortunately $d's are still not handled in MM-PA.  This is an item on my to-do list but is a somewhat big project.  So the book's comment stands.

**Comment by david-a-wheeler** [comment]
Ok! Closing out
