### ISSUE TITLE
Are we done?

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#199]
Are we done with version 2 of the book?

I don't know of anything else we need to do.  I'm sure there's more review we could do, and there's always "one more bug".  But at some point we need to say, "ship it".

So I *think* we're done.  Anyone else?

**Comment by david-a-wheeler** [comment]
If so, we need to request an ISBN number, update the number in the .tex file, and see if there's a problem on Lulu when submitting it.

**Comment by benjub** [comment]
As far as I'm concerned, this is done.  Thanks for taking care of the edits.  (Sorry for the delay, I was away from my computers for a few days.)

**Comment by david-a-wheeler** [comment]
@benjub - my sincere thanks for taking the time to report all those items!

**Comment by EdwardMcCants** [comment]
I've got an issue I noticed yesterday... new issue incoming

**Comment by david-a-wheeler** [comment]
@EdwardMcCants - Thanks, we got it in.  We're about to go to publication, so *now* is time time to report on any problems!

**Comment by david-a-wheeler** [comment]
I think we're done.  Anyone with a last-minute change better be *fast*.
