### ISSUE TITLE
Address Marnix Klooster's comments

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#20]
Review this:

~~~~
  10/13/05 - metamath.tex - see Marnix Klooster's comments
     (***SEE 10/13/05 - 10/14/05 EMAILS)
~~~~

This may already be done.

**Comment by nmegill** [comment]
This has long been fixed in the program, and I'm pretty sure I fixed the Compressed Proof appendix in metamath.tex around that time.  Let me look at it before you do anything about this.  It can probably be marked closed but I'll let you know.

**Comment by david-a-wheeler** [comment]
That's good news.  If it's okay in the .tex file, just close this issue.

**Comment by david-a-wheeler** [comment]
I will make a separate PR to address Marnix Klooster's earlier comment to explain further why Unification is especially easy.

**Comment by david-a-wheeler** [comment]
Done.
