### ISSUE TITLE
92 or 93 non-$ characters?

### ISSUE THREAD

**Issue by nmegill** [metamath/metamath-book#204]
p. 112 says, "A math symbol token may consist of any combination of the 92 printable standard ascii characters other than space or $ ."  Since there are 94 printable characters other than space, subtracting the "$" would leave 93.  The original book says 93, so this got changed somewhere along the line.  @david-a-wheeler do you agree it should be 93, and if so could you change it back?

**Comment by nmegill** [comment]
I fixed this, and also some set -> setvar cases, in commit 8407d2d.

**Comment by david-a-wheeler** [comment]
There are 95 printable characters including space.

I'm running around so I'll have to look more closely at this later.
--- David A.Wheeler
