### ISSUE TITLE
Book cover

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#208]
We need to make a book cover via Lulu.  Unfortunately, it looks like all the cover work is erased whenever you upload an updated file, due to bad website design.  So I'm going to document the settings I used in this issue, so we can reproduce and/or change things.

**Comment by david-a-wheeler** [comment]
Lulu doesn't support https on most pages, and it wants you to use flash (!).  Browsers are increasingly refusing to run flash, so that may make things challenging in the future :-(.

**Comment by david-a-wheeler** [comment]
I used the Lulu "new" cover editor as documented here: http://connect.lulu.com/en/discussion/33504/how-to-create-a-book-cover-using-the-new-lulu-cover-wizard  I laugh when they say "new" - it uses Flash, and Flash is scheduled for Internet-wide banning (it's already hard to re-enable).

Here's what I did to create a cover:

Layout tab: Selected 4th entry (Title on top, picture, then author names)

Themes: Selected "Geared".

Background: I can't seem to get *both* gears and a color, so I'm skipping it.

Cover front:

Title text: ("Metamath: A Computer Language for Mathematical Proofs").
The default was Century Gothic, 40pt, bold,and the line break was bad.
I changed it to Arial 36pt, and forced a line break after the colon.

Authors: Default was Lindsey Pro 21 (Yuk!), bold.
I changed it to be Arial 36pt.

The title & author text is in white.  I tried black, but it wasn't easier to read so I left it as White.

I want to put the Aleph-sub-0 image on the front.  However, I need it transparent, and ideally in vector format (it's not clear that the system can handle vector formats).

Spine:
Spine Title text default is Century Gothic 10. I highlighted the text & enlarged it to Century Gothic 12 (hopefully making the book easier to find).

Spine Author text default is Century Gothic 10, and by default only shows first author.  I changed the text to "Norman Megill & David A. Wheeler", and changed the size (not the font family) to Century Gothic 12.   I think the two items are far enough apart on the spine that they're obviously independent, and if I made them any bigger that'd be a problem.

To be continued...

**Comment by david-a-wheeler** [comment]
On the back cover:

I put the abstract it.  That was complicated, copy/paste often failed. I turned it into a single line (using vi), used notepad to "copy" from the menu, then could control-V in it to paste it.

Default abstract font is Lindsey Pro 12 (ugh). I changed it to Bembo 14 (better at least).

I changed the default top-right text to Arial 14pt, and used this text:
~~~~
Metamath: A Computer Language for Mathematical Proofs

Norman Megill &
David A. Wheeler
~~~~

I created an image that is a combination for Norm & my pictures, uploaded it, and dragged that into an area on the back cover.  It's probably a little pixellated, but I don't have better images.  I used black fills on the top & bottom because a rescaled image would look wrong.

**Comment by david-a-wheeler** [comment]
For the front image I created an aleph _ 0 image with red text and yellow outline using Powerpoint, took a printscreen enlarged as much possible, and then uploaded it.  That's the standard image for Metamath overall... so I think we should use it.

I created a horizontal merge our our mugs for the back using Microsoft Paint.  No one's going to call Hollywood once they see it (except to issue an alert), but it humanizes the cover.

**Comment by david-a-wheeler** [comment]
@nmegill - it took a lot longer to make a cover than I expected, but I have one.

Please take a look at the proposed cover for the 2019 Metamath book:  https://dwheeler.com/misc/24804269_cover.pdf

If anyone has any comments I'd like to hear them!!

**Comment by nmegill** [comment]
> For the front image I created an aleph _ 0 image with red text and yellow outline using Powerpoint
I'm not sure what you did, but there is a higjher resolution logo here:
http://us.metamath.org/mmbig.gif

> https://dwheeler.com/misc/24804269_cover.pdf
This file gives a Forbidden message.

**Comment by david-a-wheeler** [comment]
On Sun, 02 Jun 2019 15:05:57 -0700, nmegill <notifications@github.com> wrote:
> > https://dwheeler.com/misc/24804269_cover.pdf
> This file gives a Forbidden message.

Whups! Sorry about that.  Please try again!

> > For the front image I created an aleph _ 0 image with red text and yellow outline using Powerpoint
> I'm not sure what you did, but there is a higjher resolution logo here:
> http://us.metamath.org/mmbig.gif

I used Powerpoint to generate a good-looking image.  The bitmapped image I created is 1920x1080.

The "mmbig.gif" isn't very big, it's only 320x320.  I think it'll look a little ugly when scaled up to book size.  Do you have a bigger one, or can you generate a bigger one?

--- David A. Wheeler

**Comment by nmegill** [comment]
OK, the cover pdf is accessible now.

A couple of comments: 

The aleph is a somewhat different shape than the Metamath logo.  Perhaps it would be better to start from mmbig.gif?

The abstract has unusually large space between some of the words because of the large font.  Should we use ragged-right?  I've seen that before on some back cover blurbs, maybe for this reason.

**Comment by nmegill** [comment]
> The "mmbig.gif" isn't very big, it's only 320x320. I think it'll look a little ugly when scaled up to book size. Do you have a bigger one, or can you generate a bigger one?

Unfortunately no.  mmbig.gif is the original from which the logo was derived.  I wonder if some graphics experts on the google group could smooth the jaggedness.  I'll post a comment on the group.

**Comment by david-a-wheeler** [comment]
@nmegill - it was easy to switch the abstract to ragged-right, so I did so.  That solved the word inter-spacing problem.  So that's resolved.  We have space for another sentence if there's something else important we want to say (though there's nothing wrong with a short abstract!!).

I tried the mmbig.gif logo.  It looks *terrible*.  In fact, the tool is showing a big warning triangle about using the image. I had to tweak it a little, because the cover system doesn't support transparent images, but that was the easy part.

We could try to smooth out the jaggedness with a blur (e.g., a Gaussian blur).  But that's nontrivial, and I'm not sure the result will be worth it... you'll tend to have nicer images if you *start* with a nice image.

Where did you get mmbig.gif?  I presume you didn't draw it.

**Comment by david-a-wheeler** [comment]
@nmegill - I uploaded an updated cover, now with ragged right abstract, but the same front image.

**Comment by nmegill** [comment]
> We could try to smooth out the jaggedness with a blur (e.g., a Gaussian blur). But that's nontrivial, and I'm not sure the result will be worth it... you'll tend to have nicer images if you _start_ with a nice image.

I have Photoshop 7 where Gaussian blur is easy, but I don't think that's the right approach.  Ideally it should be converted to an SVG file with smooth curves.  Let's see if anyone responds to my google group post.

> 
> Where did you get mmbig.gif? I presume you didn't draw it.

I blew up an aleph from somewhere and printed it out as a guide, then drew the aleph and boundaries on a tracing paper overlay, then scanned it and cleaned it up.  The originals from that effort are long gone.

**Comment by nmegill** [comment]
I created a 960x960 and 1600x1600 here using bicubic sampling on the 320x320:
http://us2.metamath.org/mm960x960.gif
http://us2.metamath.org/mm1600x1600.gif
It is still jagged but the edges are smoothed a little.

**Comment by benjub** [comment]
On the front cover, I would write the subtitle smaller than the title (as a by product, it would fit on two lines), and maybe remove the colon.

**Comment by david-a-wheeler** [comment]
I changed the subtitle to 30pts, and now the subtitle fits on two lines.

I need to leave the colon in.  Amazon is *really* picky & insists that the book metadata *exactly* match what's on the front cover.  I'm even concerned about the aleph-null, though I think the fact that it's not English & it's in color should make it obvious that this is a *picture*.

**Comment by david-a-wheeler** [comment]
Unfortunately, the 1600x1600 version is still hideous.  It just isn't designed to scale up to book size.

You can take a look here: https://dwheeler.com/misc/24804269_cover-1.pdf

I strongly recommend we revert to the aleph0 I made.

**Comment by david-a-wheeler** [comment]
I figure out how to use my approach to create an image that looks more like the website's, while still avoiding ugliness.  Take a look at this image:

https://dwheeler.com/images/aleph0-2.png

I think this will look good.  It's a big image on the front cover, so we want it to look reasonable!

**Comment by david-a-wheeler** [comment]
The key differences are that the glow is more prominent & it now has a black outline.  I can easily make the black outline thicker if you'd like.

**Comment by david-a-wheeler** [comment]
Okay, here's yet another cover.  This one uses my "aleph0", but with more glow and a black outline so it looks more like the one on the website.  I *could* make the outline thicker, but on the book cover I think it looks odd when it's that thick.

Anyway, here's the latest version:
https://dwheeler.com/misc/24804269_cover-2.pdf

**Comment by nmegill** [comment]
Can the 0 subscript be made smaller?  If you look at typical set theory books it's often quite small.

Another thing to consider is whether we want the aleph dominating the page.  I like the background of gears, but the aleph doesn't seem to blend in with it too well.  It doesn't necessarily have to be the logo colors if another color scheme helps it blend in better.  Perhaps make the whole thing shades of brown similar to the background, including the border (the sold black seems to clash with the subtle bowns of the background).  Just some thoughts...

If we had an artist, I might suggest something like having an aleph_0 (not necessarily the logo one) emerge from the gears (computer) that grind away, to eventually and miraculously produce the actual completed infinity aleph_0, which is something ordinary computer arithmetic can't do.  (I used to be in awe of that.) But I think that is beyond our capabilities. :)

**Comment by david-a-wheeler** [comment]
The 0 subscript can easily be made smaller.  How much smaller do you want it? 50% current size? 75%?

I think it's very important that the color scheme of the aleph 0 does *NOT* change.  The aleph 0 as shown is the logo / brand of Metamath - it's on practically every page, and has been for years.  It's okay to regenerate it, as I have done, but I tried to make it obvious that it's the "same".  If anything I'd make the gears match the logo colors, but I can't do that - I don't get to change the color of the book if we use the gears, and the gears both look good & make sense in this context.

We can make the *aleph 0* smaller as a whole, however, we can't change the size of the white area it's in.  The "cover wizard" I'm using is very useful (because I'm not a graphical designer), but it's also very limiting.  I think making the aleph 0 smaller as a whole would look lousy, because the whitespace would dominate.  Remember, the aleph 0 with those colors & such are the Metamath logo/brand - it's perfectly appropriate to emphasize it on the cover of the book.  If anything, it makes a strong statement: A huge logo like that, front and center, is hard to forget.

I love the idea of aleph_0 emerging from the gears.  That would be fantastic.  But it's definitely beyond my capabilities.  Let's do that after we have miliions of Metamath users :-).

**Comment by nmegill** [comment]
Here is a quick low-res mockup of a possible color scheme that is coordinated with the background:
http://us2.metamath.org/cover-concept2.jpg

**Comment by david-a-wheeler** [comment]
The external orange rectangular frame is fine.  But the orange surrounding the logo looks terrible.

I think you *should* have the Metamath logo "pop out" in the book.   You want to help busy people easily remember the front cover.  The current form "pops out" with surrounding white, just like it already does on the web pages.

**Comment by nmegill** [comment]
Here's another idea where I first restored the white logo background, then changed all while including the title to a very light shade:
http://us2.metamath.org/cover-concept3.jpg
Again, this is just a quick and dirty mock up to convey the general idea (there are artifacts around the edges of the logo I didn't spend time to suppress).  The exact colors and everything else can be adjusted of course.  We don't necessarily have to have a border around the aleph.

I guess the overall sense that I have with the original cover is that the pure blacks, pure whites, and primary colors seem to clash with the (rather nice, I think) subtle brown shades of the background.

Anyone else have an opinion?

**Comment by nmegill** [comment]
> The 0 subscript can easily be made smaller. How much smaller do you want it? 50% current size? 75%?

Here is the one from Takeuti & Zaring.  Others I looked at have similar ratios.
http://us2.metamath.org/aleph0-tz.gif

The Metamath logo's subscript 0 seems even smaller, but if it matches T&Z more or less that should be OK.

**Comment by nmegill** [comment]
I've given my opinion about the cover; take from it whatever you want.  I'll go with what you prefer.

In the back cover abstract, the right edge is very jagged (explaining the excessive spacing in the right-justified version).  A significant improvement can be made if we hyphenate "mathematics":

_essentially all of\<line break\>
mathematics_

can be changed to

_essentially all of math-\<line break\>
ematics_

and "fundamentals":

_the\<line break\>
fundamentals_

can be changed to

_the funda-\<line break\>
mentals_

**Comment by tirix** [comment]
Hi David,

The cover says "_the MPE database has over 20,000 proven theorems_".
An actual count would be more than 23,000, including only the "main part" of set.mm.
If you include mathboxes, it goes up to 32,000. And iset.mm, has more than 5000 theorems.

You may prefer to round up, I just wanted to make sure you had considered updated that number which might be outdated. One could even add "at the time of printing", to show that the database is very much alive and grows continuously!

**Comment by giomasce** [comment]
If it's still useful, I can try to do some Inkscape magic on the Aleph-zero symbol and work out a scalable version, that can then be rendered at any resolution without loss. I'm not really an expert, but I've already done similar things with somewhat acceptable results.

**Comment by nmegill** [comment]
@giomasce As you can see from the conversations, we're not completely settled on what version will go on the cover, but certainly a scalable version would be good to have for future applications, and would be most appreciated.  Yes, mmbig.gif is the highest resolution version available.

**Comment by giomasce** [comment]
[There it is](https://people.debian.org/~gio/mmlogo.svg): not perfect, but probably reasonable. If you want some specific detail to be fixed I can try to touch it. I do not claim any copyright on this image and accept to release it on whatever terms the original image had.

**Comment by nmegill** [comment]
Excellent, thanks @giomasce!  And thanks for the copyright release.  It has been uploaded here:
http://us2.metamath.org/copyright.html#logo

**Comment by david-a-wheeler** [comment]
That's fantastic @giomasce ! Would it be possible to create a second .svg with that same awesome logo and the word "Metamath" centered below it, suitable for T-shirts and mugs?

**Comment by david-a-wheeler** [comment]
Something's wrong, I cannot get this to open: http://us2.metamath.org/mmlogo.gif

**Comment by nmegill** [comment]
> Something's wrong, I cannot get this to open: http://us2.metamath.org/mmlogo.gif

Try it now.

**Comment by nmegill** [comment]
BTW mmlogo.gif is the just the old 320x320 mmbig.gif renamed with a more meaningful name.  (It got corrupted when I regen'ed the us2 site today do to a mistake.)  I left it there in case anyone has issues working with svg files, but I expect the svg to be the standard reference.

**Comment by david-a-wheeler** [comment]
> The cover says "the MPE database has over 20,000 proven theorems". An actual count would be more than 23,000, including only the "main part" of set.mm. If you include mathboxes, it goes up to 32,000. And iset.mm, has more than 5000 theorems.

I think "over 23,000" is safest, but I'll switch to that.  Mathboxes are obviously more, and I did say it was just MPE.

**Comment by david-a-wheeler** [comment]
> I've given my opinion about the cover; take from it whatever you want. I'll go with what you prefer.

Let's try another go with the stark white background for the logo.  That's how it shows on all the Metamath pages.  I switched to the cleaner .svg file; it took me a while to get a version I could use.  (They don't accept SVG files, which is rediculous.)  We could switch to something other than white, but if it's too muted doesn't pop off the page.

I made a new version of our photos.  It took me a bit to create a version with the right scaling.

**Comment by david-a-wheeler** [comment]
>  A significant improvement can be made if we hyphenate ...

You're right, that is definitely a big improvement.

**Comment by david-a-wheeler** [comment]
We have yet another draft cover:

https://dwheeler.com/misc/24804269_cover-3.pdf

Thoughts?

The version of aleph null I used was generated from the .svg file and turned into this file: https://dwheeler.com/images/mmbig-tweaked-3.png via https://dwheeler.com/images/mmlogo.html (which is a weird way to do it but it worked).

**Comment by giomasce** [comment]
@david-a-wheeler No problem. Is there an official font to use? Or do you have any preference?

**Comment by giomasce** [comment]
For the moment I have made [an example with Linux Libertine](https://people.debian.org/~gio/mmlogo2.svg), trying to emulate the original logo's style.

**Comment by nmegill** [comment]
> We have yet another draft cover:
> 
> https://dwheeler.com/misc/24804269_cover-3.pdf

It looks much better.  I still think the aleph-0 is too dominant for my taste, but I can go with it.  (Maybe I'm fatigued of seeing the logo for 25 years, but other people have said they like it.  One advantage is that it is relatively easy to identify the Metamath page with a bunch of browser tabs open.)

If it's not too hard, could my photo be cropped/zoomed so our heads are roughly the same size?

**Comment by benjub** [comment]
It's true that such a large logo on the cover could make people think that Metamath is a cult, with Norm as the guru !  More seriously, the logo could be made a bit smaller (and the black rectangular frame maybe slightly thinner and/or less black: the whole thing looks a bit aggressive).

As for the edition, it's indeed a "Second Edition" or a "Second, revised and expanded Edition", even if the subtitle is slightly different.  Maybe the first edition could be put in the References and \cited on page xiv, line -5:
"The present edition" --> "The 2005 edition (\cite{first-ed})"

**Comment by david-a-wheeler** [comment]
> More seriously, the logo could be made a bit smaller (and the black rectangular frame maybe slightly thinner and/or less black: the whole thing looks a bit aggressive).

I cannot change the black rectangular frame.  Its color & width are fixed by the layout wizard I'm using from the publisher.

I'll try to make the logo a *little* bit smaller, but not much so.  I think it is very important that the symbol be dominant in its frame.  This *is* the logo, and it should be very prominently placed.  In addition, it would look weird for it to be small relative to its background.... the symbol is the point, not the background.  Also, in many cases people will only see thumbnails, so it's important that the logo be clearly understandable even when it's greatly minimized, and the logo is pretty complicated so it needs to be large to be understandable when minimized.

In this context, aggressive is good.  In fact, I think it's necessary.

There's a time & place for being humble & self-effacing.  The cover of a book is not an appropriate time or place.  The primary purpose of a book cover is to say "read me!" to potential readers, in competition with a sea of millions of other books and their covers.  It took time to make the book, let's encourage people to actually read it.  A cover is no guarantee, but it's something we can (and should) control.

I think very it's important that the logo be very prominent, and Norm can live with its size as-is, so I think a minor downscale (while leaving it large) is a reasonable place to end up.

> If it's not too hard, could my photo be cropped/zoomed so our heads are roughly the same size?

I'll try.  That will require a rescale, and that has the potential of making the picture less clear.  I intentionally chose size multiples to avoid rescaling.  But the originals have a lot of pixels, so it may be just fine (I was being conservative about image quality).

> As for the edition, it's indeed a "Second Edition"

Fair enough.  I explained why I didn't include edition information, but I noted it because I wasn't sure.  Okay, I'll add "Second Edition" (unless Norm objects).

> Maybe the first edition could be put in the References and \cited on page xiv, line -5: "The present edition" --> "The 2005 edition (\cite{first-ed})"

We could do that.  I *think* we can replace the contents without starting over with cover (I hope).  We'll need to figure out exactly what the contents should say, updating things is a pain even if I don't have to start over with the cover.

**Comment by david-a-wheeler** [comment]
@giomasce - I like your example with Linux Libertine!!  It's quite distinctive.  Are you willing to release its copyright like the other one?

This is fundamentally Norm's project, so I think we need his okay.  So...

@nmegill - what do you think about the example by @giomasce here?: [Metamath logo with name](https://people.debian.org/~gio/mmlogo2.svg).  Is that suitable for mugs, T-shirts, and other stuff?

**Comment by david-a-wheeler** [comment]
@giomasce - just after I posted I took another look, and realized that the font you used is a serif font. I think sans serif looks much better on large headings like this; we don't need to help people's eyes track many words in a line in this context.  Would you mind making another version but with some Libre font that's sans serif?  Thanks/sorry!

**Comment by giomasce** [comment]
I tried with Linux Biolinum: [the result is here](https://people.debian.org/~gio/mmlogo3.svg). It looks better to me indeed. I also moved the writing a bit closer to the aleh-zero. For the copyright, I accept to release to the Public Domain all of these, just like the first one. From my understanding of the OFL license for the Linux Libertine and Biolinum fonts, we don't have any other obligation, since we are using the font curves, but not distributing or modifying the font itself.

**Comment by david-a-wheeler** [comment]
@giomasce - I think the new version with Linux Biolinum looks fantastic, and thanks for the release!

@nmegill - what do you think? Thumbs up?

**Comment by nmegill** [comment]
> @nmegill - what do you think? Thumbs up?

Yes, I like it.

**Comment by david-a-wheeler** [comment]
@nmegill - Excellent! I see that you already posted it on the [copyright page](http://us2.metamath.org/copyright.html#logo) - thanks!

**Comment by david-a-wheeler** [comment]
Back to the endless tweaking of the book cover :-).

I reduced the Metamath logo size by 10% (600units to 540 units), and rescaled Norm's head :-).

New book cover is here - this okay?:

https://dwheeler.com/misc/24804269_cover-4.pdf

I think we should *not* add a new citation to the first edition.  There's already a lengthy discussion of various changes to the book, and I fear that changing the book contents may cause me to have redo the cover :-(.   That would be no fun.  I'll redo the contents if there's a serious problem, but I don't think anyone will wonder what a "Second Edition" means.  There's a title change, but the title change is so slight that I think no one will care.  It's not like there are millions of Metamath books published before this one, and people might have trouble figuring out which one we meant.

**Comment by nmegill** [comment]
The new cover is good.

I agree that a citation to the first edition is probably unnecessary.  I don't recall seeing that in other books, although maybe I didn't pay attention to it.  Sometimes it is mentioned in the Preface, or there will be a "Preface to the Second Edition."

...

There is one little nit that has occurred to me.  The book's development of set theory never gets as far as cardinal numbers (which is OK), and the book doesn't even have the word "aleph". so the symbol on the cover might be a mystery to non-mathematicians who might wonder if it's some sort of cult symbol. :)

If we do have to modify the text yet again,  perhaps we should also add (suggest bottom of 2nd page), maybe in italics,

```
Cover:   Aleph null ($\aleph_0$) is the symbol for the first infinite
cardinal number, discovered by Georg Cantor in 1873.
```

**Comment by david-a-wheeler** [comment]
Page 2 (copyright page) is a good place for it.  We'll need to move your name up to ensure that it all stays on one page.  I think we can make this new text *not* centered.

However, if we're going to mention the cover image, we should also mention *why*, and credit the logo's creators (as requested on the Copyright page).

Proposed new version:

> Cover:   Aleph null ($\aleph_0$) is the symbol for the first infinite
cardinal number, discovered by Georg Cantor in 1873.
We use a red aleph null (with black outline and gold glow) as the Metamath logo.
Credit: N. Megill (1994) and G. Mascellani (2019), public domain.

**Comment by david-a-wheeler** [comment]
If we add that, we probably need to add some index entries. E.g.:

{aleph null} {infinite cardinal number, first} {Metamath logo}, {Cantor, Georg}, {Mascellani, G.}

**Comment by nmegill** [comment]
It seems a little obsessive with detail but OK.  The outline isn't black but dark grey; maybe say "dark outline" instead of "black outline".

**Comment by david-a-wheeler** [comment]
It took 26,323 steps to prove that 2+2=4.  Being obsessed with detail is practically a prerequisite around here :-).

**Comment by david-a-wheeler** [comment]
I added the information about the cover in PR #211.  Since I'm changing the book anyway, I slipped in a mention about the term "Second edition" and the former book title.

I'm hoping that's enough.

Is it all okay?  Are we done? (I'd *like* to be done :-) ).

**Comment by david-a-wheeler** [comment]
Book cover is done. I'm closing this issue.
