### ISSUE TITLE
Book description

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#210]
We must provide info about the book.

We must pick a book category.  There's no "mathematics" category.  Options are:

* Computers & Internet
* Crafts & Hobbies
* Education & Language
* Engineering
* Entertainment
* Games
* Medicine & Science
* Reference

Of these lousy categories, I think "Computers & Internet" is the closest.

We must enter keywords separated by commas.  (Short two to three word phrases are recommended.)  Here are my keywords:

> Metamath, mathematics, proofs, mathematical proofs, proof verifier, proof verification, rigor, formalization, formalizing theorems, formal methods, foundations of mathematics, logic, propositional calculus, predicate calculus, set theory, axiomatic.

(We run out of room soon after that.)

Description (I used our abstract):

> Metamath is a computer language and an associated computer program for archiving, verifying, and studying mathematical proofs.  The Metamath language is simple and robust, with an almost total absence of hard-wired syntax, and we believe that it provides about the simplest possible framework that allows essentially all of mathematics to be expressed with absolute rigor.  While simple, it is also powerful; the Metamath Proof Explorer (MPE) database has over 23,000 proven theorems and is one of the top systems in the “Formalizing 100 Theorems” challenge.  This book explains the Metamath language and program, with specific emphasis on the fundamentals of the MPE database.

Copyright: Norman Megill & David A. Wheeler

Released as: Public Domain.

I did *not* claim an edition.  Technically the name of the book has changed.  Should I have added "Second Edition"?

For the publisher I entered:

> Lulu Press

Comments?

**Comment by benjub** [comment]
"Technically", the title has changed, but "morally", this is a "Second Edition", or "Second, revised and expanded Edition".

I would remove "rigor" from the keywords, as overly general (and the list is already quite long).

**Comment by david-a-wheeler** [comment]
Okay, I can add "Second edition".

You *want* the keyword list to be as long as allowed.  This isn't something normal readers read, it's metadata used by search systems to help potential readers find the book at all. Every added keyword (phrase) increases the likelihood that someone will find it when they're looking for it.  If there's something other than "rigor" that would be better at helping potential readers find the book, I'd like to know.

**Comment by david-a-wheeler** [comment]
I'm adding second edition, and the keyword list should be long.  So I'm closing this.
