### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#214]
On page 138, there is a superfluous comma: "... option to hide, them, but today ...".

If there will be a revision after the publishing proofs, this could be corrected. If there will be no revision, it can be corrected in the next edition...

**Comment by david-a-wheeler** [comment]
@nmegill - I agree.  If we revise & create another proof, we should do this.  But I don't think we need to delay publication for this superfluous comma.  There's no mathematical error here.

**Comment by nmegill** [comment]
I agree.

**Comment by david-a-wheeler** [comment]
Included in errata.
