### ISSUE TITLE
Redundant information in section 5.6.3

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#215]
The examples are mentioned twice:

"(An example where this must be on would
be a system that implements a Deduction Rule and in which deductions from
empty assumption lists would be permissible. The MIU-system described in
Appendix D is another example.) Note that empty substitutions are always
permissible in proof verication (VERIFY PROOF...) outside the Proof
Assistant. (See the MIU system in the Metamath book for an example of
a system needing empty substitutions; another example would be a system
that implements a Deduction Rule and in which deductions from empty
assumption lists would be permissible.)"

I think the first bracketed text could simply be removed.

**Comment by david-a-wheeler** [comment]
This is section 5.6.3 `set empty_substitution` *Command*.

I agree that this is a duplication, and I think we should fix it later for the paper-only publications.

I would have gladly fixed this earlier.  But there is no serious mathematical error here, and we've already sent the proofs.

@nmegill - I don't think we need to delay publication for this.  Do you agree?

**Comment by nmegill** [comment]
I agree.

**Comment by david-a-wheeler** [comment]
Included in errata.
