### ISSUE TITLE
Book nitpicks that don't matter

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#216]
Now that I'm re-reading the proofs, I found a few minor things:

* Section 1.4.2 - there's an extraneous ")" after the term `set.mm`.
* Section 3.3.2 and 3.3.3 headings - the headings go far past the intended margin (though they're quite readable).

These should be fixed at some point, but I don't think they need to delay publication.

@nmegill - agree?

**Comment by nmegill** [comment]
I agree.

**Comment by david-a-wheeler** [comment]
Included in errata.
