### ISSUE TITLE
See if we should use amsmath package instead

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#4]
Norm Megill said:

> There are some arcane macros in metamath.tex to wrest control of math
> symbols from LaTeX, which originally typeset logic formulas poorly. The
> more recent amsmath package provides much better control over equation
> typesetting, and we may want to switch to that. We can revisit this and
> some other issues when the time comes, and I'll help with those things.

**Comment by david-a-wheeler** [comment]
The current arcane macros in metamath.tex are a real mess.  At the least, they make the source code hard to read.  Also, I can't figure out how to insert `<_\mathbb{R}` into the complex and real number axioms... if they were in `$...$` it woud be trivial.  So I would *like* to get rid of the arcane stuff.

However: I don't really understand why the macros are there. Adding `\usepackage{amsmath}` or similar is obviously easy.  Using `$...$` is easy.  What problems are the arcane things trying to avoid?

It's possible that things have been fixed in the last ~20 years, and they're just unnecessary.

**Comment by nmegill** [comment]
The book was originally written with an older version of LaTeX before 2e, and amsmath either didn't exist or I wasn't aware of it.  The provided {eqnarray} environment was very inflexible and designed for normal math equations, not logic.  Every formula was rigidly assumed to be two terms connected with a relation like = or \le.  It was impossible to get things aligned correctly if they weren't of that form.  It was out of frustration with {eqnarray} that led me to write the macros to be able to put the symbols where I wanted them.  Another feature of the macros was automatically wrapping lines that were too long, which I saw necessary for automated generation of long formulas without a lot of manual tweaking and fine tuning.  I agree it was an ugly solution and preferably should be replaced eventually.

amsmath has the {align} environment that gives you very good control over the layout.  Here is a quick example I copy/pasted from a document with ZFC axioms.  I'm won't claim this is the best layout, but it will give you an idea of the {align} syntax.

```
\begin{align}
\text{\rm (Ext)} & & &
  \forall z ( z \in x \,\leftrightarrow\, z \in y ) \,\to\, x = y
\label{eq:ax-ext}
\\
\text{\rm (Rep)} & & &
\forall w \exists y \forall z ( \forall y \varphi \,\to\, z = y )
      %\notag \\  & & & \qquad
\,\to\, \exists y \forall z ( z \in y \,\leftrightarrow\, \exists w ( w \in x
\wedge \forall y \varphi ) )
\label{eq:ax-rep}
\\
\text{\rm (Un)} & & &
  \exists y \forall z ( \exists w ( z \in w \wedge w \in x ) \,\to\, z
\in y)
\label{eq:ax-un}
\\
\text{\rm (Pow)} & & &
 \exists y \forall z ( \forall w ( w \in z \,\to\, w \in x )
\,\to\, z \in y)
\label{eq:ax-pow}
\\
\text{\rm (Reg)} & & &
\exists y \,y \in x \,\to\, \exists y ( y \in x \wedge \forall z (
z \in y \,\to\, \lnot z \in x ) )
\label{eq:ax-reg}
\\
\text{\rm (Inf)} & & &
 \exists y ( x \in y \wedge \forall z ( z \in y \,\to\, \exists w ( z
\in w \wedge w \in y ) ) )
\label{eq:ax-inf}
\\
\text{\rm (AC)} & & &
 \exists y \forall z \forall w ( ( z \in w
\wedge w \in x ) \,\to\,
      \notag \\  & & & \ \
   \exists v \forall u ( \exists t ( ( u \in w \wedge w \in t )
 \wedge ( u \in t
\wedge t \in y ) ) \,\leftrightarrow\, u = v ))
\label{eq:ax-ac}
\end{align}
```

**Comment by nmegill** [comment]
BTW in metamath.exe, 'show statement xxx/tex' produces an {align} environment containing direct math symbols and 'show statement xxx/old_tex' (deprecated) encloses symbols in macros like in the current Metamath book.  The output of 'show statement .../tex' is meant as a convenience to get the initial LaTeX code and may be edited by hand to wrap long lines or for better appearance. 

(Note that metamath.exe 0.171 has a bug related to these commands, fixed today in 0.172.)

**Comment by david-a-wheeler** [comment]
Some experiments are here:

https://github.com/metamath/metamath-book/pull/36

Both breqn and autobreak do not work, at least not within an align :-(.

**Comment by david-a-wheeler** [comment]
I have to give up.  I can't get it working the way I want.  Let's keep the system that works, and I'm closing this issue.
