### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#6]
@nmegill - can you please enable Travis on metamath-book?  It should be obvious how to enable checkers from the front page of https://github.com/metamath/metamath-book .

I suspect you want to go here:
https://github.com/marketplace/category/continuous-integration

I can then set up a few TeX checkers.

**Comment by nmegill** [comment]
> @nmegill - can you please enable Travis on metamath-book? It should be obvious how to enable checkers from the front page of https://github.com/metamath/metamath-book .
> 
> I suspect you want to go here:
> https://github.com/marketplace/category/continuous-integration
> 
> I can then set up a few TeX checkers.

@david-a-wheeler  I was unable to find where to set up Travis.

**Comment by david-a-wheeler** [comment]
Ah! I think I figured out how to enable Travis on the repo.  Now I need to set up a YAML file, but that's a different story.

**Comment by david-a-wheeler** [comment]
Travis is all set, we have a CI test, and if it fails the build fails.

The tests and Travis script can be improved forever, but we have the basics. At this point we'll detect many kinds of future problems.

I'm closing this issue.
