### ISSUE TITLE
Implement spec changes 1-7

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#7]
Per Norm Megill:

> One of the most important parts of the book is the 4-page Metamath spec pp. 92-95. In particular, almost every verifier was written using only these 4 pages, even by programmers who have little understanding of Metamath at a higher level.

> I see that not filed under "metamath.tex" in my to-do list is a set of proposed spec changes (mainly minor clarifications or restrictions that don't affect much in practice). These will require small changes to the spec, which will hopefully remain 4 pages. :)

Proposed spec changes #1-#7 are at:
https://groups.google.com/d/msg/metamath/ZlRle52FVO0/7TqSetEtCQAJ

**Comment by david-a-wheeler** [comment]
Additional comments from Norm Megill:

> I have decided that change #7 ($e forbidden in outermost scope) should NOT be implemented - it has no real justification and complicates the spec needlessly.

Also, regarding markup:

> In the spec on p. 93, it says: "Two special characters inside comments, \` and \~, control the typesetting of comments and are discussed on p. 119. They may be ignored for the purpose of parsing." The markup
conventions are not part of the language and shouldn't be explicitly mentioned in the spec proper, especially since markup is more elaborate now. Mentioning that they may be ignored is also redundant: everything is ignored until "$)" appears. Just a brief pointer to p. 119 should suffice.

DAW: I think the markup conventions should be documented, but *separately*, since most verifiers can ignore them.

> The documentation for much of the new markup is in http://us.metamath.org/mpeuni/mmnotes.txt e.g. the 21-Dec-2017 entry for modularization (file inclusions) and 11-May-2016 for the "discouraged" stuff. Much of this could probably be used verbatim with some small cleanup for a nicer LaTeX presentation. Also, "help verify markup" in metamath.exe tells where to get more information on the various markup features.

**Comment by david-a-wheeler** [comment]
They are:

~~~~
I'm fine with disallowing global $e but think we should keep global
$d's.  See
https://groups.google.com/d/msg/metamath/A2p5GPDwXxw/JIn_Z3YVCAAJ for
how this can be used to emulate individual variables (instead of
metavariables ranging over them).

Here is a collection of proposed changes and clarifications to the
Metamath 1.0 spec collected from various emails.

1. Comments have highest parse precedence e.g. "$( $[ $)" is a comment
and does not violate item 4 below.  Nested comments will continue to be
disallowed e.g. "$( $( $)" is not allowed.

2. $[ ... $] is allowed only in the outermost scope i.e. not between ${ $}.

3. $[ ... $] may not occur inside of a statement (e.g. may not occur
between the label of a $a statement and its $.).

4. $( without a matching $) or $[ without a matching $] may not occur in
an included file.

5. An incomplete statement (e.g. $a but no $.) may not occur in an
included file.

6. The type declared for a variable by a $f statement is effectively
global, even if the variable is not (e.g.  "wff P" in one local scope
and "class P" in another is not allowed).

7. A $e statement may not occur in the outermost scope. 
~~~~

**Comment by nmegill** [comment]
AFAIK the spec has no prohibition on $d in the outermost scope.  (If there is, it should be removed.)  So it is already allowed.

If we want to talk about using global $d to emulate object-language variables, that should be done in a different section on applications, not in the spec.  The spec should contain exactly and only what is needed to verify that the language is syntactically correct and that proofs verify.

**Comment by david-a-wheeler** [comment]
I completely agree that no-prohibition on $d should continue.  I copied-and-pasted it in for context.
