### ISSUE TITLE
Split up definitions discussion

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#70]
The section on definitions is long, try to split it up further into subsubsections. E.g., discuss first just classes.  Also, make it clear that although classes can be THOUGHT of as collections of sets, we don't actually commit to their reality.

**Comment by jkingdon** [comment]
If you can come up with a way of explaining set.mm style classes, I'm all for it. At least for me, a statement like "set.mm doesn't allow quantifying over classes" is clearer than something about their "reality", but I'm not sure I've been especially good at explaining this either.

**Comment by david-a-wheeler** [comment]
I've extended the discussion about classes a little bit, though I'm not sure I've achieved @jkingdon 's aims :-).

I've decided to not subdivide the definitions further.

**Comment by jkingdon** [comment]
Sounds good. I'd need to spend more time with the text (both in the book and the website) to have much more to say.
